
# Site Settings

title: Alberto´s blog  # Your Title 
subtitle: .NET Cloud Solutions Architect 
email: arferraces@gmail.com  # Your Email
description: >-  
  No he fallado, solo he encontrado 10.000 caminos que no funcionaban
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arodriguezf.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ferraces
github_username:  arodriguezf
locale:           es_es
encoding:         utf-8

# Navigation 

urls:
    - text: About
      url: /
    - text: Blog
      url: /blog
    # - text: Sample Page
    #   url: /sample-page
    # - text: Contact Me
    #   url : /contact

# Author Details

author_logo: albertorf.jpg
author: Alberto Rodríguez Ferraces
author_bio: Mi nombre es Alberto y soy desarollador de software especializado en tecnologías Microsoft.  
# author_email: "arferraces@gmail.com"
author_location: Spain
author_website_url: "http://arferraces.com"

# social links
twitter_username: ferraces
github_username:  arodriguezf
linkedin_username: arferraces

# Choose what to show ( true - display or false - don't display)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: true

author_work_experiences: 
            - company_name: Tokiota
              company_logo: tokiota.jpg
              company_url: https://www.tokiota.com/
              designation: .NET Cloud Solutions Architect
              description: Desarrollo de software en diferentes proyectos con tecnologías Microsoft
              visibility: true
            # - company_name: Microsoft
            #   company_logo: microsoft.png
            #   company_url: https://microsoft.com
            #   designation: Azure Developer
            #   description: Worked on various Azure Cloud Products
            #   visibility: true

author_education_details:
              # - college_logo: mit.png
              #   college_name: MIT
              #   college_url: https://mit.org
              #   college_degree: CS Engineer
              #   description: Bachelor of Technology
              #   visibility: true

author_project_details:
              - project_thumbnail: pontemaker.png
                project_title: Pontemaker
                project_description: Asociación de makers de la provincia de Pontevedra
                project_url: https://www.facebook.com/PonteMaker/
                visibility: true
              # - project_thumbnail: programmingebooks.png
              #   project_title: Programming Ebooks
              #   project_description: A Platform to easily find and read programming books
              #   project_url: https://programmingebooks.com
              #   visibility: true
                
#for comments using disqus
# disqus_shortname: alberto  

# wakatime username
# wakatime_username: alberto

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# pagination of posts
paginate: 4
per_page: 5
paginate_path: "/blog/page/:num/"

# Search ( add algolia credentials below )
algolia:
  application_id: D9WA1YKTRS # add your algolia app id
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: [] 
  nodes_to_index: 'article' 
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9b # add algolia search only api key 


# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Shop 

# collections:
#  - products

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build